In [2]:
from scipy.spatial import distance_matrix
from scipy.cluster.hierarchy import dendrogram, linkage
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

### Metodo K Means Python
* Kk Means debe saber a Priori cuantos K grupos debe tener antes de analizar

In [7]:
data= np.random.random(90).reshape(30,3)
data

array([[0.54690293, 0.75845725, 0.40693562],
       [0.84429477, 0.56954866, 0.19053273],
       [0.5494156 , 0.11235986, 0.11420505],
       [0.04910938, 0.54622701, 0.69234719],
       [0.07101279, 0.34602496, 0.63499327],
       [0.57974553, 0.53160477, 0.30505963],
       [0.48272484, 0.86542016, 0.5587936 ],
       [0.33291317, 0.81415924, 0.46722704],
       [0.79188368, 0.25815849, 0.57303903],
       [0.52197557, 0.19382821, 0.30108102],
       [0.10489855, 0.6626103 , 0.83896082],
       [0.80440501, 0.45084159, 0.84988541],
       [0.11789697, 0.00735591, 0.97040092],
       [0.07898782, 0.56672114, 0.99808553],
       [0.47760222, 0.67089046, 0.3484867 ],
       [0.56456876, 0.29615845, 0.55053709],
       [0.28723004, 0.75369478, 0.59529457],
       [0.34973848, 0.25932111, 0.75414169],
       [0.09343942, 0.20634343, 0.65200152],
       [0.81280467, 0.70088059, 0.28745819],
       [0.92847084, 0.41444865, 0.91349937],
       [0.81336011, 0.63952993, 0.83432014],
       [0.

In [12]:
# Elegir 2 centroides al azar par calcular su distancia
c1= np.random.choice(range(len(data)))
c2= np.random.choice(range(len(data)))

clust_center=np.vstack([data[c1], data[c2]])
clust_center

array([[0.5494156 , 0.11235986, 0.11420505],
       [0.79188368, 0.25815849, 0.57303903]])

In [15]:
from scipy.cluster.vq import vq
vq(data,clust_center)

(array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 0]),
 array([0.58129576, 0.49600588, 0.        , 0.8055629 , 0.72884408,
        0.43770815, 0.68157822, 0.72868851, 0.        , 0.20570045,
        0.84038339, 0.33753145, 0.82161821, 0.88549192, 0.56528247,
        0.23156513, 0.70762054, 0.47779903, 0.70480087, 0.52725418,
        0.39874291, 0.46278854, 0.44924247, 0.45307574, 0.41321959,
        0.53847634, 0.37023936, 0.32441083, 0.17771488, 0.80769658]))

In [19]:
from scipy.cluster.vq import kmeans
kmeans(data,clust_center)
#Información de lso varicentros  
# El numero final es el error cuadrado  normalizado de cada uno de los puntos.

(array([[0.65258962, 0.28397181, 0.34720444],
        [0.40528439, 0.55716076, 0.69005594]]),
 0.36942756484220174)

In [22]:
kmeans(data, 2)



(array([[0.63344381, 0.51504227, 0.50386884],
        [0.17517437, 0.32153963, 0.7054518 ]]),
 0.36438036430896953)